# This is a basic workflow to help you get started with Actions

name: PublishToBeamer

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.8.0

      with:
        url: 'https://api.getbeamer.com/v0/posts'
        method: 'POST'
        customHeaders: '{ "Beamer-Api-Key" : "${{ secrets.BEAMER_API_KEY }}" }'
        data: '{ "title": [ "${{github.repository}} Updated!" ], "content": [ "We just updated ${{github.repository}}. Check it out!" ], "category": "new", "publish": true, linkUrl": [ "https://github.com/${{github.repository}}" ], "linkText": [ "${{github.repository}}" ], "linksInNewWindow": true  }'
